drop table nastavnici;
drop table predmeti;
drop table studenti;
drop table upisi;

CREATE TABLE studenti (
	id number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	jmbag number(10) NOT NULL UNIQUE,
	ime varchar2(20) NOT NULL,
	prezime varchar2(20) NOT NULL,
	email varchar2(20) NOT NULL UNIQUE,
	password varchar2(10) NOT NULL,
	spol number(10) NOT NULL
    CONSTRAINT spol_ck CHECK (spol between 0 and 1)
);

CREATE TABLE nastavnici (
	id number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	ime varchar2(20) NOT NULL,
	prezime varchar2(30) NOT NULL,
	email varchar2(30) NOT NULL UNIQUE,
	password varchar2(20) NOT NULL,
	spol number(10) NOT NULL
    CONSTRAINT spol_ck1 CHECK (spol between 0 and 1)

);

CREATE TABLE predmeti (
	id number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	IDnastavnika number(10) NOT NULL,
	sifra varchar2(10) NOT NULL UNIQUE,
	naziv varchar2(30) NOT NULL,
	ects number(10) NOT NULL,
	semestar number(10) NOT NULL
    CONSTRAINT semestar_ck CHECK (semestar between 1 and 6)
);

CREATE TABLE upisi (
	id number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	IDpredmeta number(10) NOT NULL,
	IDstudenta number(10) NOT NULL,
	datum date NOT NULL,
	ocjena number(10)
    CONSTRAINT ocjena_ck CHECK (ocjena between 1 and 5)
);

ALTER TABLE predmeti ADD CONSTRAINT predmeti_fk1 FOREIGN KEY (IDnastavnika) REFERENCES nastavnici(id);
ALTER TABLE upisi ADD CONSTRAINT upisi_fk1 FOREIGN KEY (IDpredmeta) REFERENCES predmeti(id);
ALTER TABLE upisi ADD CONSTRAINT upisi_fk2 FOREIGN KEY (IDstudenta) REFERENCES studenti(id);