DROP TABLE EVIDENCIJA;
DROP TABLE TVRTKE;
DROP TABLE UCENICI;

CREATE TABLE ucenici
(
    id       number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    ime      varchar2(20)                                   NOT NULL,
    prezime  varchar2(40)                                   NOT NULL,
    email    varchar2(40)                                   NOT NULL UNIQUE,
    password varchar2(30)                                   NOT NULL
);

CREATE TABLE tvrtke
(
    id       number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    tvrtka   varchar2(40)                                   NOT NULL
);

CREATE TABLE evidencija
(
    id       number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    iducenik number(10)                                     NOT NULL,
    idtvrtka number(10)                                     NOT NULL,
    dolazak  timestamp with time zone                       NOT NULL,
    odlazak  timestamp with time zone                       NOT NULL,
    ocjena   number(10)                                     NOT NULL,
    komentar varchar2(255)                                  NOT NULL,
    CONSTRAINT ocjena_ck1 CHECK ( ocjena BETWEEN 1 AND 5)
);

ALTER TABLE evidencija
    ADD CONSTRAINT evidencija_fk1 FOREIGN KEY (iducenik) REFERENCES ucenici (id);
ALTER TABLE evidencija
    ADD CONSTRAINT evidencija_fk2 FOREIGN KEY (idtvrtka) REFERENCES tvrtke (id);