INSERT INTO UCENICI (IME, PREZIME, EMAIL, PASSWORD)
SELECT DISTINCT
    TRANSLATE(IME, 'ČĆŽŠĐčćžšđ', 'CCZSDčćžšđ') AS IME,
    TRANSLATE(PREZIME, 'ČĆŽŠĐčćžšđ', 'CCZSDčćžšđ') AS PREZIME,
    LOWER(SUBSTR(TRANSLATE(IME, 'ŠĐČĆŽšđčćž', 'SDCCZsdccz'), 1, 1)
        || TRANSLATE(PREZIME, 'ŠĐČĆŽšđčćž', 'SDCCZsdccz') || '@vub.hr') AS EMAIL,
    '12345' AS PASSWORD
FROM DATAPOOL;

INSERT INTO TVRTKE (TVRTKA) SELECT DISTINCT TVRTKA FROM DATAPOOL;

--NE ZNAM KAKO
--INSERT INTO EVIDENCIJA (IDUCENIK, IDTVRTKA, DOLAZAK, ODLAZAK, OCJENA, KOMENTAR) SELECT ???

select * from UCENICI;
select * from TVRTKE;
select * from EVIDENCIJA;