--drop table
DROP TABLE cameras CASCADE CONSTRAINTS;

--table
CREATE TABLE cameras
(
    camera_id  number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url  varchar2(200),
    category   varchar2(50),
    name       varchar2(100)                                  NOT NULL,
    price      number(10, 2)                                  NOT NULL,
    stock      number(10, 0) DEFAULT 0,
    created_at date       DEFAULT SYSDATE                     NOT NULL,
    updated_at date
);

--constraints
ALTER TABLE cameras
    ADD CONSTRAINT ck_price CHECK (price > 0);
ALTER TABLE cameras
    ADD CONSTRAINT ck_stock CHECK (stock >= 0);

--trigger
CREATE OR REPLACE TRIGGER cameras_before_update
    BEFORE UPDATE
    ON cameras
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
