ALTER TABLE order_items
    DROP CONSTRAINT order_items_fk1;

DROP TABLE order_items CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE cameras CASCADE CONSTRAINTS;
DROP TABLE lenses CASCADE CONSTRAINTS;
DROP TABLE equipment CASCADE CONSTRAINTS;
DROP TABLE films CASCADE CONSTRAINTS;

CREATE TABLE cameras
(
    camera_id  number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar2(200),
    category   varchar2(50),
    name       varchar2(100)                                  NOT NULL,
    price      number(10, 2)                                  NOT NULL,
    stock      number(10, 0) DEFAULT 0 NOT NULL,
    created_at date       DEFAULT SYSDATE                     NOT NULL,
    updated_at date
);

CREATE TABLE lenses
(
    lens_id    number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar2(200),
    category   varchar2(50),
    aperture   varchar2(50)                                   NOT NULL,
    name       varchar2(100)                                  NOT NULL,
    price      number(10, 2)                                  NOT NULL,
    stock      number(10, 0) DEFAULT 0                        NOT NULL,
    created_at date          DEFAULT SYSDATE                  NOT NULL,
    updated_at date
);

CREATE TABLE equipment
(
    equipment_id number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url    varchar2(200),
    category     varchar2(50),
    name         varchar2(100)                                  NOT NULL,
    price        number(10, 2)                                  NOT NULL,
    stock        number(10, 0) DEFAULT 0                        NOT NULL,
    created_at   date          DEFAULT SYSDATE                  NOT NULL,
    updated_at   date
);

CREATE TABLE films
(
    film_id    number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    image_url  varchar2(200),
    category   varchar2(50),
    name       varchar2(100)                                  NOT NULL,
    price      number(10, 2)                                  NOT NULL,
    stock      number(10, 0) DEFAULT 0                        NOT NULL,
    created_at date          DEFAULT SYSDATE                  NOT NULL,
    updated_at date
);

CREATE TABLE customers
(
    customer_id number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    first_name  varchar2(50),
    last_name   varchar2(50),
    email       varchar2(100)                                  NOT NULL UNIQUE,
    address     varchar2(200),
    city        varchar2(50),
    zip         varchar2(10),
    created_at  date DEFAULT SYSDATE                           NOT NULL,
    updated_at  date
);

CREATE TABLE orders
(
    order_id         number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    customer_id      number(10)                                     NOT NULL,
    order_date       date                                           NOT NULL,
    status           varchar2(20)                                   NOT NULL,
    total_amount     number(10, 2)                                  NOT NULL,
    shipping_address varchar2(200),
    payment_method   varchar2(30),
    created_at       date DEFAULT SYSDATE                           NOT NULL,
    updated_at       date
);

CREATE TABLE order_items
(
    order_item_id number(10, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    order_id      number(10)                                     NOT NULL,
    product_type  varchar2(20)                                   NOT NULL,
    product_id    number(10)                                     NOT NULL,
    quantity      number(10)                                     NOT NULL,
    unit_price    number(10, 2)                                  NOT NULL,
    total_price   number(10, 2)                                  NOT NULL,
    created_at    date DEFAULT SYSDATE                           NOT NULL,
    updated_at    date
);

-- constraints
ALTER TABLE cameras
    ADD CONSTRAINT ck_priceC CHECK (price > 0);
ALTER TABLE cameras
    ADD CONSTRAINT ck_stockC CHECK (stock >= 0);

ALTER TABLE lenses
    ADD CONSTRAINT ck_priceL CHECK (price > 0);
ALTER TABLE lenses
    ADD CONSTRAINT ck_stockL CHECK (stock >= 0);

ALTER TABLE equipment
    ADD CONSTRAINT ck_priceE CHECK (price > 0);
ALTER TABLE equipment
    ADD CONSTRAINT ck_stockE CHECK (stock >= 0);

ALTER TABLE films
    ADD CONSTRAINT ck_priceF CHECK (price > 0);
ALTER TABLE films
    ADD CONSTRAINT ck_stockF CHECK (stock >= 0);

ALTER TABLE orders
    ADD CONSTRAINT orders_fk1 FOREIGN KEY (customer_id) REFERENCES customers (customer_id);
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'));
ALTER TABLE orders
    ADD CONSTRAINT ck_total_amount
        CHECK (total_amount >= 0);

ALTER TABLE order_items
    ADD CONSTRAINT order_items_fk1 FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE;
ALTER TABLE order_items
    ADD CONSTRAINT ck_order_items_quantity
        CHECK (quantity > 0);
ALTER TABLE order_items
    ADD CONSTRAINT ck_order_items_unit_price
        CHECK (unit_price >= 0);
ALTER TABLE order_items
    ADD CONSTRAINT ck_order_items_total_price
        CHECK (total_price >= 0);
ALTER TABLE order_items
    ADD CONSTRAINT ck_order_items_product_type
        CHECK (product_type IN ('Camera', 'Lens', 'Film', 'Equipment'));

-- triggers
CREATE OR REPLACE TRIGGER cameras_before_update
    BEFORE UPDATE
    ON cameras
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

CREATE OR REPLACE TRIGGER lenses_before_update
    BEFORE UPDATE
    ON lenses
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER films_before_update
    BEFORE UPDATE
    ON films
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER equipment_before_update
    BEFORE UPDATE
    ON equipment
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER customers_before_update
    BEFORE UPDATE
    ON customers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER orders_before_update
    BEFORE UPDATE
    ON orders
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER order_items_before_update
    BEFORE UPDATE
    ON order_items
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/